const List<String> traits = [
  "sexy",
  "undead",
  "happy",
  "thick",
  "short",
  "tall",
  "skinny",
  "muscular",
  "cute",
  "old",
  "pierced",
  "tattooed",
  "scarred",
  "moody",
  "sad",
  "sick",
  "grumpy",
  "cruel",
  "dumb",
  "aroused",
  "dirty",
  "dangerous",
  "shaved",
  "sweet",
  "creepy",
  "innocent",
  "vicious",
  "heavy",
  "brave",
  "carefree",
  "caring",
  "devoted",
  "gentle",
  "helpful",
  "polite",
  "mature",
  "magical",
  "rude",
  "selfish",
  "clumsy",
  "lazy",
  "cold",
  "busy",
  "scary-looking",
  "kind",
  "imaginative",
  "optimistic",
  "pessimistic",
  "unreliable",
  "shy",
  "loud",
  "bald",
  "broke",
  "rich",
];
const List<String> jobs = [
  "flower shop owner",
  "programmer",
  "dad",
  "genius",
  "teacher",
  "office worker",
  "taxi driver",
  "bus driver",
  "old man",
  "killer",
  "secretary",
  "student",
  "idol",
  "influencer",
  "patissier",
  "chef",
  "doctor",
  "hazardous materials removal worker",
  "biker",
  "fitness trainer",
  "animator",
  "astronaut",
  "attorney",
  "babysitter",
  "barber",
  "biologist",
  "butcher",
  "cellist",
  "dancer",
  "prince",
  "doorman",
  "entrepreneur",
  "farmer",
  "dermatologist",
  "firefighter",
  "game designer",
  "interpreter",
  "business angel",
  "magician",
  "model",
  "nurse",
  "poet",
  "politician",
  "researcher",
  "tailor",
  "waiter",
  "zookeeper",
  "principal",
  "sales trainer",
  "bike courier",
  "pick-up artist instructor",
  "rental boyfriend",
  "professional mourner",
  "sailor",
  "siren",
  "merman",
  "wolf man",
  "wizard",
  "hero",
  "demon lord",
  "alpha",
  "omega",
  "sword master",
  "knight",
  "grim reaper",
  "god",
  "angel",
  "alien",
];
const List<String> actions = [
  "have a fight",
  "shake hands",
  "hold hands",
  "come out",
  "confess at the same time",
  "meet again after 800 years",
  "fall in love at first sight",
  "gaze at each other awkwardly",
  "huddle for warmth",
  "help an old lady out",
  "swap bodies",
  "swap clothes",
  "whisper into each other's ears",
  "touch foreheads",
  "fall asleep",
  "hug",
  "watch the stars",
  "take turns making breakfast for each other",
  "go strawberry picking",
  "complain about their neighbor's taste in music",
  "show memes to each other",
  "find out that they're currently reading the same book",
  "bump into each other and accidentally switch phones",
  "reach for the same flower",
  "have a staring contest",
  "have to share a table",
  "share an umbrella",
  "can suddenly hear each other's thoughts",
  "get lost",
  "have an accident",
  "ignore each other",
  "have been together for 10 years",
  "try to seduce one another",
  "adopt a pet",
  "win against evil",
  "play a game",
  "go fishing",
];
const List<String> places = [
  "at the aquarium",
  "at the art museum",
  "at the book shop",
  "in a hat shop",
  "at the movies",
  "at the local park",
  "at the zoo",
  "at home",
  "at a school dance",
  "in a forest",
  "in a cave",
  "at the beach",
  "at an amusement club",
  "at an orchestra concert",
  "at a water fountain",
  "at a pizza parlor",
  "at a magic show",
  "at the hospital",
  "at a funeral",
  "in bed",
  "at a laser tag tournament",
  "in the car",
  "on an empty bus",
  "on a crowded train",
  "at school",
  "at the flower shop",
  "at a bar",
  "at the bakery",
  "inside a closet",
  "on a park bench",
  "on the way home",
  "at the gym",
  "during pottery class",
  "at the office after hours",
  "during the zombie apocalypse",
  "after being reborn",
  "at sunrise",
  "during cooking class",
  "on Valentine's Day",
  "in the castle",
  "in a carriage",
  "on a mountain",
  "before their adventure",
  "in space",
];
